--------------------------------------------------------------------------------
-- File Name:      module2.vhd
-- Project:        Ultrasonic Parking Sensor / Proximity Alarm (or similar)
-- Target Device:  DE10-Lite or other FPGA
-- Tool Versions:  Quartus Prime / ModelSim
--
-- Description:
--   This module adjusts a periodic output signal (e.g., for a buzzer tone or 
--   a flashing LED) based on the measured distance. It uses:
--     1) A lookup table function (d2b_LUT) from LUT_pkg to translate the 
--        distance (in 13-bit STD_LOGIC_VECTOR) into a desired period (integer).
--     2) A downcounter that counts down from 'period' to zero, producing a 
--        pulse (zero => '1') each time it reaches zero.
--     3) A specialized 2-bit PWM (PWM_SEVENSEG) that uses the downcounter’s 
--        pulse (pwm_enable) to toggle output frequency or flash rate.
--
-- Ports:
--   reset_n  : in  STD_LOGIC
--       Active-low reset signal for both the downcounter and PWM.
--
--   clk      : in  STD_LOGIC
--       System clock feeding the downcounter and PWM processes.
--
--   distance : in  STD_LOGIC_VECTOR (12 downto 0)
--       The measured distance value from the ADC_data or other module.
--       Used by d2b_LUT to derive an integer 'period' for the downcounter.
--
--   output   : out STD_LOGIC
--       The final PWM-style signal whose frequency (or duty cycle) depends on 
--       the distance. Typically connected to a buzzer or flashing logic.
--
-- Internal Signals:
--   period              : integer
--       The downcounter reload value, derived from distance via d2b_LUT.
--
--   downcounter_output  : std_logic
--       A pulse from the downcounter that goes high each time the counter hits 0.
--
--   output_pwm          : std_logic
--       The raw PWM signal generated by PWM_SEVENSEG; assigned to 'output'.
--
-- Components (declared here, defined externally):
--   1) downcounter
--   2) PWM_SEVENSEG
--   3) LUT_pkg (contains the function d2b_LUT for converting distance to period)
--
-- Revision:
--   Revision 0.01 - File Created
--   Additional Comments:
--     - The 'width => 2' in PWM_SEVENSEG suggests a 2-bit duty_cycle. 
--       Currently hard-coded to "10" = decimal 2, for a 50% duty cycle.
--     - The resulting waveform frequency depends on how often downcounter_output
--       toggles, which is controlled by 'period'.
--     - If you want to vary the duty cycle in addition to frequency, you could
--       dynamically assign different 2-bit values to 'duty_cycle'.
--------------------------------------------------------------------------------

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- LUT_pkg must be accessible at compile time (contains d2b_LUT function).
library work;
use work.LUT_pkg.all;

entity module2 is
    port(
        reset_n  : in  std_logic;                           -- Active-low reset
        clk      : in  std_logic;                           -- System clock
        distance : in  std_logic_vector(12 downto 0);       -- Distance input
        output   : out std_logic                            -- PWM/Buzzer output
    );
end module2;

architecture Behavioral of module2 is

    ----------------------------------------------------------------------------
    -- Internal Signals
    ----------------------------------------------------------------------------
    signal period            : integer;
    signal downcounter_output: std_logic;   -- Goes high when downcounter hits 0
    signal output_pwm        : std_logic;   -- Internal PWM output

    ----------------------------------------------------------------------------
    -- Component Declarations
    ----------------------------------------------------------------------------
    component downcounter is
        port(
            clk     : in  std_logic;    -- Clock to be divided
            reset_n : in  std_logic;    -- Active-low reset
            enable  : in  std_logic;    -- Active-high enable
            zero    : out std_logic;    -- Pulses high when count reaches zero
            period  : in  integer       -- Reload value
        );
    end component;

    component PWM_SEVENSEG is
        generic(width : integer);
        port(
            reset_n           : in  std_logic;
            clk               : in  std_logic;
            duty_cycle        : in  std_logic_vector(width-1 downto 0);
            pwm_enable        : in  std_logic;
            inverted_pwm_out  : out std_logic
        );
    end component;

begin
    ----------------------------------------------------------------------------
    -- period <= d2b_LUT(...) 
    --   - Convert 'distance' to an integer 'period' using the LUT function.
    --   - This ensures the frequency of 'downcounter' pulses changes with distance.
    ----------------------------------------------------------------------------
    period <= d2b_LUT(to_integer(unsigned(distance)));

    ----------------------------------------------------------------------------
    -- downcounter:
    --   - Counts down from 'period' to 0, then asserts 'zero' for one cycle.
    --   - 'enable' is tied to '1' here, so it's always counting.
    ----------------------------------------------------------------------------
    downcounter_instantiation : downcounter
        port map(
            clk     => clk,
            period  => period,
            enable  => '1',
            reset_n => reset_n,
            zero    => downcounter_output
        );

    ----------------------------------------------------------------------------
    -- PWM_SEVENSEG:
    --   - width => 2 => duty_cycle is 2 bits wide (0..3).
    --   - The 'pwm_enable' input is driven by the 'downcounter_output' pulse,
    --     effectively making the PWM flip states at a rate controlled by 'period'.
    --   - "10" = decimal 2 => a nominal 50% duty cycle for 2-bit range [0..3].
    ----------------------------------------------------------------------------
    PWM_SEVENSEG_instantiation : PWM_SEVENSEG
        generic map (width => 2)
        port map(
            clk               => clk,
            pwm_enable        => downcounter_output,
            reset_n           => reset_n,
            duty_cycle        => "10",  -- Hard-coded 2-bit value (2 => 50% duty)
            inverted_pwm_out  => output_pwm
        );

    ----------------------------------------------------------------------------
    -- Assign the internal PWM signal to the module output.
    ----------------------------------------------------------------------------
    output <= output_pwm;

end Behavioral;
